"""
Django settings for jobportal project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
import certifi

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR.parent, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-&t40s26-x@xa%fjwqj0m9#c)5w*%dh4$&_#7km8#n9#e+cps+3')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Production Security Settings
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Support for MongoDB via environment variable
MONGODB_URI = os.getenv("MONGODB_URI")
if MONGODB_URI:
    # Ensure certifi is used for SSL
    os.environ['SSL_CERT_FILE'] = certifi.where()
    
    # MongoDB specialized field
    DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'
    
    # PATCH: Fix "unhashable" error in Django 6.0 + MongoDB
    import django.db.models.base
    _old_hash = django.db.models.base.Model.__hash__
    def _new_hash(self):
        if self.pk is None:
            return id(self)
        return _old_hash(self)
    django.db.models.base.Model.__hash__ = _new_hash
    
    # PATCH: Fix "Model instances must be saved" error during migration
    # This happens because Django 6.0 is strict about related filters needing saved instances,
    # and MongoDB backend might not populate PK immediately in signals.
    import django.db.models.fields.related_lookups as related_lookups
    _old_get_normalized_value = related_lookups.get_normalized_value
    def _new_get_normalized_value(value, lhs):
        from django.db.models import Model
        if isinstance(value, Model) and getattr(value, 'pk', None) is None:
            return (value, None)
        return _old_get_normalized_value(value, lhs)
    related_lookups.get_normalized_value = _new_get_normalized_value

    from django.db.models.signals import post_migrate
    from django.contrib.auth.management import create_permissions
    post_migrate.disconnect(create_permissions, dispatch_uid="django.contrib.auth.management.create_permissions")

    # Do NOT patch built-in apps' default_auto_field.
    # Built-in apps (admin, auth, contenttypes) have their own migrations
    # which expect specific primary key types. Changing them causes
    # migration sync issues and can lead to ValueErrors during migrate.
    # AdminConfig.default_auto_field = DEFAULT_AUTO_FIELD
    # AuthConfig.default_auto_field = DEFAULT_AUTO_FIELD
    # ContentTypesConfig.default_auto_field = DEFAULT_AUTO_FIELD
else:
    DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'job',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobportal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobportal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if MONGODB_URI:
    DATABASES['default'] = {
        'ENGINE': 'django_mongodb_backend',
        'HOST': MONGODB_URI,
        'NAME': os.getenv("MONGODB_NAME", "jobportal_db"),
        'OPTIONS': {
            'tlsCAFile': certifi.where(),
            'serverSelectionTimeoutMS': 5000,
            'connectTimeoutMS': 10000,
        }
    }
else:
    # Override default database if DATABASE_URL is present in the environment (Postgres fallback)
    db_from_env = dj_database_url.config(conn_max_age=600)
    if db_from_env:
        DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')